name: cd

on:
  workflow_run:
    workflows: [ ci ]
    types:
      - completed

permissions:
  contents: read

jobs:
  cd:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        location:
          - 'shani@20.16.214.172'
          - 'shani@108.143.20.222'
          - 'shani@20.16.208.103'


    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SSH client
        run: sudo apt-get install -y sshpass
      - name: upload app
        run: |
          sshpass -p 'Password123!' ssh -o StrictHostKeyChecking=no  ${{ matrix.location }}<<EOF
          
          echo '---starting update app code---'
          if [ -d sum-http-client ]; then 
              cd sum-http-client
              git pull origin main
          else
              git clone https://github.com/shaniblau/sum-http-client.git
          fi
          cd sum-http-client
          chmod 777 ../images/
          
          echo '---starting dependencies installment----'
          find ./ -type f -name "*.sh" -exec chmod +x {} \; -exec sudo mv -v {} /usr/bin/ \;
          ./install_dependencies
          pip install -r dependencies/requirements.txt
          
          
          EOF

                    

