name: cd

on:
  workflow_run:
    workflows: [ ci ]
    types:
      - completed

permissions:
  contents: read

jobs:
  cd:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        location:
          - 'shani@20.16.214.172'
          - 'shani@108.143.20.222'
          - 'shani@20.16.208.103'


    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SSH client
        run: sudo apt-get install -y sshpass
      - name: upload app
        run: |
          sshpass -p 'Password123!' ssh -o StrictHostKeyChecking=no  ${{ matrix.location }}<<EOF
          
          echo ''
          echo '----updating app----'
          cd sum-http-server
          git pull origin main
          
          echo ''
          echo '----restarting all services----'
          sudo systemctl restart http_server
   
          EOF

                    

