name: ci cd

on:
  push

permissions:
  contents: read

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        run: |
          pytest
          

  cd:

    needs: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        location:
          - 'shani@20.16.214.172'
          - 'shani@108.143.20.222'
          - 'shani@20.16.208.103'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SSH client
        run: sudo apt-get install -y sshpass
      - name: download app
        run: |
          sshpass -p 'Password123!' ssh -o StrictHostKeyChecking=no ${{ matrix.location }} <<EOF
          sudo apt-get update
          sudo apt install python3-pip
          if [ -d sum-http-server ]; then rm -r sum-http-server; fi
          git clone https://github.com/shaniblau/sum-http-server.git
          cd sum-http-server 
          sudo mv http_server.service ../../../etc/systemd/system/ 
          pip install -r requirements.txt
          sudo systemctl enable http_server.service
          sudo systemctl restart http_server
          EOF
