name: ci

on:
  push

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          cd dependencies
          chmod +x ./install_dependencies.sh
          ./install_dependencies.sh
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          cd ..
      - name: Test
        run: |
          pytest
